repos:
    - repo: local
      hooks:
          - id: pytest
            name: Run Project Tests
            entry: ./scripts/test_local
            language: system
            stages: [pre-push]
            pass_filenames: false
